//Data is of tyoe reco

Map<String, Map<String, dynamic>> getAllRecords() {
  return {
    "01": {
      "Batch Id": "1",
      "Entity": "2",
      "Region": [
        "Chandigarh",
        "Bangalore",
      ],
      "City Name": "Kolkata",
      "Area Name": "Bengal",
      "Area Name 2": "Bengal",
      "Area Name 3": "Bengal",
      "Field 0": "Value",
      "Field 1": "Value",
      "Field 2": "Value",
      "Field 3": "Value",
      "Field 5": "Value",
      "Field 6": "Value",
      "Field 7": "Value",
    },
    "02": {
      "Batch Id": "2",
      "Entity": "2",
      "Region": [
        "Chandigarh",
        "Bangalore",
      ],
      "City Name": "Kolkata",
      "Area Name": "Bengal",
      "Area Name 2": "Bengal",
      "Area Name 3": "Bengal",
      "Field 0": "Value",
      "Field 1": "Value",
      "Field 2": "Value",
      "Field 3": "Value",
      "Field 5": "Value",
      "Field 6": "Value",
      "Field 7": "Value",
    },
    "03": {
      "Batch Id": "2",
      "Entity": "2",
      "Region": [
        "Chandigarh",
        "Bangalore",
      ],
      "City Name": "Kolkata",
      "Area Name": "Bengal",
      "Area Name 2": "Bengal",
      "Area Name 3": "Bengal",
      "Field 0": "Value",
      "Field 1": "Value",
      "Field 2": "Value",
      "Field 3": "Value",
      "Field 5": "Value",
      "Field 6": "Value",
      "Field 7": "Value",
    },
    "04": {
      "Batch Id": "2",
      "Entity": "2",
      "Region": [
        "Chandigarh",
        "Bangalore",
      ],
      "City Name": "Kolkata",
      "Area Name": "Bengal",
      "Area Name 2": "Bengal",
      "Area Name 3": "Bengal",
      "Field 0": "Value",
      "Field 1": "Value",
      "Field 2": "Value",
      "Field 3": "Value",
      "Field 5": "Value",
      "Field 6": "Value",
      "Field 7": "Value",
    },
    "05": {
      "Batch Id": "2",
      "Entity": "2",
      "Region": [
        "Chandigarh",
        "Bangalore",
      ],
      "City Name": "Kolkata",
      "Area Name": "Bengal",
      "Area Name 2": "Bengal",
      "Area Name 3": "Bengal",
      "Field 0": "Value",
      "Field 1": "Value",
      "Field 2": "Value",
      "Field 3": "Value",
      "Field 5": "Value",
      "Field 6": "Value",
      "Field 7": "Value",
    },
    "06": {
      "Batch Id": "2",
      "Entity": "2",
      "Region": [
        "Chandigarh",
        "Bangalore",
      ],
      "City Name": "Kolkata",
      "Area Name": "Bengal",
      "Area Name 2": "Bengal",
      "Area Name 3": "Bengal",
      "Field 0": "Value",
      "Field 1": "Value",
      "Field 2": "Value",
      "Field 3": "Value",
      "Field 5": "Value",
      "Field 6": "Value",
      "Field 7": "Value",
    },
    "07": {
      "Batch Id": "2",
      "Entity": "2",
      "Region": [
        "Chandigarh",
        "Bangalore",
      ],
      "City Name": "Kolkata",
      "Area Name": "Bengal",
      "Area Name 2": "Bengal",
      "Area Name 3": "Bengal",
      "Field 0": "Value",
      "Field 1": "Value",
      "Field 2": "Value",
      "Field 3": "Value",
      "Field 5": "Value",
      "Field 6": "Value",
      "Field 7": "Value",
    },
    "08": {
      "Batch Id": "2",
      "Entity": "2",
      "Region": [
        "Chandigarh",
        "Bangalore",
      ],
      "City Name": "Kolkata",
      "Area Name": "Bengal",
      "Area Name 2": "Bengal",
      "Area Name 3": "Bengal",
      "Field 0": "Value",
      "Field 1": "Value",
      "Field 2": "Value",
      "Field 3": "Value",
      "Field 5": "Value",
      "Field 6": "Value",
      "Field 7": "Value",
    },
    "09": {
      "Batch Id": "2",
      "Entity": "2",
      "Region": [
        "Chandigarh",
        "Bangalore",
      ],
      "City Name": "Kolkata",
      "Area Name": "Bengal",
      "Area Name 2": "Bengal",
      "Area Name 3": "Bengal",
      "Field 0": "Value",
      "Field 1": "Value",
      "Field 2": "Value",
      "Field 3": "Value",
      "Field 5": "Value",
      "Field 6": "Value",
      "Field 7": "Value",
    },
    "10": {
      "Batch Id": "2",
      "Entity": "2",
      "Region": [
        "Chandigarh",
        "Bangalore",
      ],
      "City Name": "Kolkata",
      "Area Name": "Bengal",
      "Area Name 2": "Bengal",
      "Area Name 3": "Bengal",
      "Field 0": "Value",
      "Field 1": "Value",
      "Field 2": "Value",
      "Field 3": "Value",
      "Field 5": "Value",
      "Field 6": "Value",
      "Field 7": "Value",
    },
  };
}
